server:
  port: 8080

spring:
  application:
    name: skyops-flight-info-service

opensky:
  # Reads from env var, falls back to default for local dev
  url: ${OPENSKY_URL:https://opensky-network.org/api}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always